"""Authored synthetic fixture generator: 300 fictional rows with the 13
attribute columns of the Cleveland file, a `num` field in 0..4, and a planted
signal so that the demonstration has something to learn.

The values are drawn from simple distributions chosen for readability. They
are not fitted to any dataset and carry no information about any patient.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from heart_risk_calibration.schema import ID_COLUMN

FIXTURE_VERSION = "v1"
DEFAULT_ROWS = 300
GENERATOR = "tools/make_fixtures.py"

# Planted signal: logit of the positive class as a linear function of a few
# columns. Coefficients are the whole specification; see docs/data.md.
PLANTED_COEFFICIENTS: dict[str, float] = {
    "intercept": -2.3,
    "age_per_year_above_54": 0.03,
    "sex_male": 0.6,
    "cp_equals_4": 0.9,
    "thalach_per_bpm_below_150": 0.02,
    "oldpeak_per_unit": 0.5,
    "ca_per_vessel": 0.6,
    "thal_equals_7": 0.8,
    "exang": 0.7,
}
MISSING_ROWS_CA = 4
MISSING_ROWS_THAL = 2


@dataclass(frozen=True)
class FixtureSpec:
    seed: int
    n_rows: int
    version: str = FIXTURE_VERSION

    def as_dict(self) -> dict[str, object]:
        return {
            "seed": self.seed,
            "n_rows": self.n_rows,
            "fixture_version": self.version,
            "generator": GENERATOR,
            "planted_coefficients": dict(PLANTED_COEFFICIENTS),
            "missing_rows": {"ca": MISSING_ROWS_CA, "thal": MISSING_ROWS_THAL},
            "statement": provenance_statement(self.seed, self.version),
        }


def provenance_statement(seed: int, version: str = FIXTURE_VERSION) -> str:
    return (
        "Authored synthetic demonstration data. Fictional identifiers. Not derived "
        "from any patient, dataset, or person. Generated by `" + GENERATOR + "` with "
        f"seed `{seed}`, fixture version `{version}`."
    )


def planted_logit(frame: pd.DataFrame) -> np.ndarray:
    c = PLANTED_COEFFICIENTS
    return (
        c["intercept"]
        + c["age_per_year_above_54"] * (frame["age"] - 54.0)
        + c["sex_male"] * frame["sex"]
        + c["cp_equals_4"] * (frame["cp"] == 4).astype(float)
        + c["thalach_per_bpm_below_150"] * (150.0 - frame["thalach"])
        + c["oldpeak_per_unit"] * frame["oldpeak"]
        + c["ca_per_vessel"] * frame["ca"]
        + c["thal_equals_7"] * (frame["thal"] == 7).astype(float)
        + c["exang"] * frame["exang"]
    ).to_numpy(dtype=float)


def generate(spec: FixtureSpec) -> pd.DataFrame:
    """Return the fixture frame: patient_id, 13 attributes, num. `?` marks missing."""
    if spec.n_rows < 20:
        raise ValueError("n_rows must be at least 20 so that every class is present")
    rng = np.random.default_rng(spec.seed)
    n = spec.n_rows
    frame = pd.DataFrame({
        "age": np.clip(np.round(rng.normal(54, 9, n)), 29, 77),
        "sex": rng.integers(0, 2, n),
        "cp": rng.choice([1, 2, 3, 4], size=n, p=[0.08, 0.17, 0.28, 0.47]),
        "trestbps": np.clip(np.round(rng.normal(131, 17, n)), 94, 200),
        "chol": np.clip(np.round(rng.normal(246, 50, n)), 126, 564),
        "fbs": rng.choice([0, 1], size=n, p=[0.85, 0.15]),
        "restecg": rng.choice([0, 1, 2], size=n, p=[0.5, 0.02, 0.48]),
        "thalach": np.clip(np.round(rng.normal(150, 22, n)), 71, 202),
        "exang": rng.choice([0, 1], size=n, p=[0.67, 0.33]),
        "oldpeak": np.clip(np.round(rng.gamma(1.2, 0.9, n), 1), 0.0, 6.2),
        "slope": rng.choice([1, 2, 3], size=n, p=[0.47, 0.46, 0.07]),
        "ca": rng.choice([0, 1, 2, 3], size=n, p=[0.58, 0.22, 0.13, 0.07]),
        "thal": rng.choice([3, 6, 7], size=n, p=[0.55, 0.06, 0.39]),
    }).astype(float)
    logit = planted_logit(frame) + rng.normal(0.0, 0.8, n)
    prob = 1.0 / (1.0 + np.exp(-logit))
    positive = rng.random(n) < prob
    severity = 1 + rng.binomial(3, np.clip(prob, 0.05, 0.95))
    frame["num"] = np.where(positive, severity, 0).astype(int)
    frame = frame.astype(object)
    for col in frame.columns:
        if col != "num":
            frame[col] = [_fmt(v) for v in frame[col]]
    missing_ca = rng.choice(n, size=MISSING_ROWS_CA, replace=False)
    remaining = np.setdiff1d(np.arange(n), missing_ca)
    missing_thal = rng.choice(remaining, size=MISSING_ROWS_THAL, replace=False)
    frame.loc[missing_ca, "ca"] = "?"
    frame.loc[missing_thal, "thal"] = "?"
    frame.insert(0, ID_COLUMN, [f"SYN-P{i + 1:04d}" for i in range(n)])
    return frame


def _fmt(value: float) -> str:
    return f"{value:.1f}" if float(value) != int(value) else str(int(value))


def fixture_header(spec: FixtureSpec, source_id: str) -> str:
    return (
        f"# source_id: {source_id}\n"
        f"# {provenance_statement(spec.seed, spec.version)}\n"
        "# Columns: patient_id then the 13 attribute columns of the Cleveland file, then num (0..4).\n"
        "# `?` marks a missing value, as in the source file format.\n"
    )
